# Generated by Django 4.2.13 on 2026-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('total_pacientes', models.IntegerField(default=0)),
                ('pacientes_criticos', models.IntegerField(default=0)),
                ('pacientes_alto_riesgo', models.IntegerField(default=0)),
                ('pacientes_medio_riesgo', models.IntegerField(default=0)),
                ('pacientes_bajo_riesgo', models.IntegerField(default=0)),
                ('pacientes_hipertensos', models.IntegerField(default=0)),
                ('pacientes_diabeticos', models.IntegerField(default=0)),
                ('pacientes_fumadores', models.IntegerField(default=0)),
                ('promedio_edad', models.FloatField(default=0.0)),
                ('promedio_imc', models.FloatField(default=0.0)),
                ('promedio_glucosa', models.FloatField(default=0.0)),
                ('promedio_colesterol', models.FloatField(default=0.0)),
                ('promedio_presion_sistolica', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Snapshot Clínico',
                'verbose_name_plural': 'Snapshots Clínicos',
                'db_table': 'analytics_clinical_snapshot',
                'ordering': ['-fecha_calculo'],
            },
        ),
    ]
