# Generated by Django 4.2.13 on 2026-06-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
                ('sexo', models.CharField(default='Sin datos', max_length=20)),
                ('peso', models.FloatField(default=0.0, help_text='kg')),
                ('altura', models.FloatField(default=0.0, help_text='metros')),
                ('imc', models.FloatField(default=0.0, help_text='kg/m²')),
                ('clasificacion_imc', models.CharField(blank=True, default='', max_length=30)),
                ('presion_sistolica', models.IntegerField(default=0, help_text='mmHg')),
                ('presion_diastolica', models.IntegerField(default=0, help_text='mmHg')),
                ('frecuencia_cardiaca', models.IntegerField(default=0, help_text='bpm')),
                ('glucosa', models.FloatField(default=0.0, help_text='mg/dL')),
                ('colesterol', models.FloatField(default=0.0, help_text='mg/dL')),
                ('saturacion_oxigeno', models.FloatField(default=0.0, help_text='%')),
                ('temperatura', models.FloatField(default=0.0, help_text='°C')),
                ('antecedentes_familiares', models.BooleanField(default=False)),
                ('fumador', models.BooleanField(default=False)),
                ('consumo_alcohol', models.BooleanField(default=False)),
                ('actividad_fisica', models.CharField(default='Sin datos', max_length=50)),
                ('diagnostico_preliminar', models.CharField(default='Sin datos', max_length=200)),
                ('riesgo_enfermedad', models.CharField(choices=[('Bajo', 'Bajo'), ('Medio', 'Medio'), ('Alto', 'Alto'), ('Crítico', 'Crítico')], default='Bajo', max_length=20)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'patients_paciente',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['riesgo_enfermedad'], name='patients_pa_riesgo__0ce502_idx'), models.Index(fields=['fecha_consulta'], name='patients_pa_fecha_c_2d8b20_idx'), models.Index(fields=['sexo'], name='patients_pa_sexo_e2248a_idx')],
            },
        ),
    ]
