# Generated by Django 4.2.13 on 2026-06-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ETLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('archivo_origen', models.CharField(blank=True, max_length=255)),
                ('tipo_origen', models.CharField(choices=[('excel', 'Excel'), ('csv', 'CSV'), ('auto', 'Automático')], default='excel', max_length=10)),
                ('registros_extraidos', models.IntegerField(default=0)),
                ('registros_limpios', models.IntegerField(default=0)),
                ('duplicados_removidos', models.IntegerField(default=0)),
                ('nulos_tratados', models.IntegerField(default=0)),
                ('outliers_corregidos', models.IntegerField(default=0)),
                ('errores_tipo_corregidos', models.IntegerField(default=0)),
                ('registros_cargados', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.FloatField(default=0.0, help_text='Segundos')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EJECUTANDO', 'Ejecutando'), ('EXITOSO', 'Exitoso'), ('ERROR', 'Error')], default='PENDIENTE', max_length=15)),
                ('mensaje', models.TextField(blank=True)),
                ('detalle_errores', models.JSONField(blank=True, default=list)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etl_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log ETL',
                'verbose_name_plural': 'Logs ETL',
                'db_table': 'etl_log',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
