# Generated by Django 4.2.13 on 2026-06-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('algoritmo', models.CharField(choices=[('logistic_regression', 'Regresión Logística'), ('random_forest', 'Random Forest'), ('decision_tree', 'Árbol de Decisión')], max_length=30)),
                ('version', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('ENTRENANDO', 'Entrenando'), ('LISTO', 'Listo'), ('ERROR', 'Error')], default='ENTRENANDO', max_length=15)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('roc_auc', models.FloatField(blank=True, null=True)),
                ('matriz_confusion', models.JSONField(blank=True, default=dict)),
                ('registros_entrenamiento', models.IntegerField(default=0)),
                ('features_usadas', models.JSONField(blank=True, default=list)),
                ('ruta_archivo', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=False)),
                ('mensaje_error', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('entrenado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modelo ML',
                'verbose_name_plural': 'Modelos ML',
                'db_table': 'ml_model',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_entrada', models.JSONField(default=dict)),
                ('riesgo_predicho', models.CharField(max_length=20)),
                ('probabilidad', models.FloatField(blank=True, null=True)),
                ('probabilidades_dict', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones', to='ml.mlmodel')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones', to='patients.paciente')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Predicción',
                'verbose_name_plural': 'Predicciones',
                'db_table': 'ml_prediction',
                'ordering': ['-creado_en'],
            },
        ),
    ]
