/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated.usuarios'
import { Route as AuthenticatedReportesRouteImport } from './routes/_authenticated.reportes'
import { Route as AuthenticatedPrediccionesRouteImport } from './routes/_authenticated.predicciones'
import { Route as AuthenticatedPacientesRouteImport } from './routes/_authenticated.pacientes'
import { Route as AuthenticatedEtlRouteImport } from './routes/_authenticated.etl'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCambiarPasswordRouteImport } from './routes/_authenticated.cambiar-password'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated.auditoria'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportesRoute = AuthenticatedReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPrediccionesRoute =
  AuthenticatedPrediccionesRouteImport.update({
    id: '/predicciones',
    path: '/predicciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPacientesRoute = AuthenticatedPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEtlRoute = AuthenticatedEtlRouteImport.update({
  id: '/etl',
  path: '/etl',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCambiarPasswordRoute =
  AuthenticatedCambiarPasswordRouteImport.update({
    id: '/cambiar-password',
    path: '/cambiar-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cambiar-password': typeof AuthenticatedCambiarPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etl': typeof AuthenticatedEtlRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/predicciones': typeof AuthenticatedPrediccionesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/cambiar-password': typeof AuthenticatedCambiarPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/etl': typeof AuthenticatedEtlRoute
  '/pacientes': typeof AuthenticatedPacientesRoute
  '/predicciones': typeof AuthenticatedPrediccionesRoute
  '/reportes': typeof AuthenticatedReportesRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/cambiar-password': typeof AuthenticatedCambiarPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/etl': typeof AuthenticatedEtlRoute
  '/_authenticated/pacientes': typeof AuthenticatedPacientesRoute
  '/_authenticated/predicciones': typeof AuthenticatedPrediccionesRoute
  '/_authenticated/reportes': typeof AuthenticatedReportesRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/auditoria'
    | '/cambiar-password'
    | '/dashboard'
    | '/etl'
    | '/pacientes'
    | '/predicciones'
    | '/reportes'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/auditoria'
    | '/cambiar-password'
    | '/dashboard'
    | '/etl'
    | '/pacientes'
    | '/predicciones'
    | '/reportes'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/auditoria'
    | '/_authenticated/cambiar-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/etl'
    | '/_authenticated/pacientes'
    | '/_authenticated/predicciones'
    | '/_authenticated/reportes'
    | '/_authenticated/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reportes': {
      id: '/_authenticated/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof AuthenticatedReportesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/predicciones': {
      id: '/_authenticated/predicciones'
      path: '/predicciones'
      fullPath: '/predicciones'
      preLoaderRoute: typeof AuthenticatedPrediccionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pacientes': {
      id: '/_authenticated/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof AuthenticatedPacientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etl': {
      id: '/_authenticated/etl'
      path: '/etl'
      fullPath: '/etl'
      preLoaderRoute: typeof AuthenticatedEtlRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cambiar-password': {
      id: '/_authenticated/cambiar-password'
      path: '/cambiar-password'
      fullPath: '/cambiar-password'
      preLoaderRoute: typeof AuthenticatedCambiarPasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedCambiarPasswordRoute: typeof AuthenticatedCambiarPasswordRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEtlRoute: typeof AuthenticatedEtlRoute
  AuthenticatedPacientesRoute: typeof AuthenticatedPacientesRoute
  AuthenticatedPrediccionesRoute: typeof AuthenticatedPrediccionesRoute
  AuthenticatedReportesRoute: typeof AuthenticatedReportesRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedCambiarPasswordRoute: AuthenticatedCambiarPasswordRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEtlRoute: AuthenticatedEtlRoute,
  AuthenticatedPacientesRoute: AuthenticatedPacientesRoute,
  AuthenticatedPrediccionesRoute: AuthenticatedPrediccionesRoute,
  AuthenticatedReportesRoute: AuthenticatedReportesRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
