# Generated by Django 4.2.13 on 2026-06-17 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pacientes', 'Reporte de Pacientes'), ('etl', 'Reporte ETL'), ('analitica', 'Reporte Analítica'), ('ml', 'Reporte Machine Learning'), ('criticos', 'Reporte Pacientes Críticos')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], max_length=10)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('filas', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Reporte',
                'verbose_name_plural': 'Logs de Reportes',
                'db_table': 'reports_log',
                'ordering': ['-creado_en'],
            },
        ),
    ]
